import OpenAI from 'openai';


const client = new OpenAI({
  apiKey: process.env['OPENAI_API_KEY'],
});

const generateDescription = async (imageUrl) => {
  return client.chat.completions.create({
    messages: [
      {
        role: 'system',
        content: `You are an AI assistant that helps users to generate descriptions from image and you have to generate description in bengali and english language both in two json key. Your answer should be 1 paragraph long. You should describe the image in a way that is helpful for a police report.`,
      },
      {
        role: 'user',
        content: [
          {
            type: 'text',
            text: 'You will seen an image and you have to describe the image, there is a high chance that the image will be a picture of a crime scene. Some one will report that crime using your description. So, you have to be very careful about the description.',
          },
          {
            type: 'image_url',
            image_url: {
              url: imageUrl,
            },
          },
        ],
      },
    ],
    model: 'gpt-4o-mini',
    max_tokens: 400,
    temperature: 0.7,
  });
};

const analyzeSentiment = async(texts)=> {
    const userContent = [];

    texts.forEach((text) => {
        userContent.push({
            role: 'user',
            content: text,
        });
    });
  return client.chat.completions.create({
    messages: [
      {
        role: 'system',
        content: `analyze sentiment that using the text that is generated by the AI, the text is in Bengali language, you have analyze sentiment that the text indicates it is a crime scene or not, or crime scene related text or not, based on that you have to return the sentiment score as well, and you also will return the result by saying it's a CRIME or FAKE, if the sentiment score is greater than 0.6 then it's a CRIME otherwise it's FAKE. Your ans should be in english and using a valid json. check some of example of the result below between ###. don't use between ~~~ this example format as result.
                
        ###
        {
            "sentiment_score": 0.75,
            "result": "CRIME"
        }
        ###
        
        ###
        {
            "sentiment_score": 0.3,
            "result": "FAKE"
        }
        ###  


        ~~~
        json
        {
            "sentiment_score": 0.8,
            "result": "CRIME"
        }
        ~~~

        `,
      },
        ...userContent,
    ],
    model: 'gpt-4o-mini',
    temperature: 0.8,
  });
}

export const AiServices = {
    generateDescription,
    analyzeSentiment,
}